spring:
  r2dbc:
    url: 'r2dbc:postgresql://172.20.74.195:5432/postgres'
    username: 'postgres'
    password: 'postgres'
  liquibase:
    url: 'jdbc:postgresql://172.20.74.195:5432/postgres'
    user: 'postgres'
    password: 'postgres'
    change-log: classpath:db/changelog/liquibase-changelog.xml
